name: Deploy On VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          debug: true
          script: |
            set -e
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
             nvm use 20.19.5
             cd /var/www/${{ secrets.VPS_DOMAIN }}/fe-portfolio
             git pull origin main
             rm -f .env
             echo "${{ secrets.ENV_FILE }}" > .env
             npm install
             npm run build
             sudo systemctl restart nginx
             echo "Build completed"
